# This file was generated by GoReleaser. DO NOT EDIT.
class TrussCli < Formula
  desc ""
  homepage ""
  version "0.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/instructure-bridge/truss-cli/releases/download/v0.0.8/truss-cli_0.0.8_Darwin_x86_64.tar.gz"
    sha256 "522e4c348524eff549dc586639505733277153cfd78871c8bf03741c3a7bcf4d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/instructure-bridge/truss-cli/releases/download/v0.0.8/truss-cli_0.0.8_Linux_x86_64.tar.gz"
      sha256 "1a67c3ff3b4c6762af167cd55f2730f9965879a99e579989d7d1ddc3bc18a355"
    end
  end
  
  depends_on "kubectl"
  depends_on "vault"
  depends_on "sshuttle"

  def install
    system "cp", "truss-cli", "truss"
    bin.install "truss"
  end

  test do
    system bin/"truss", "help"
  end
end
